### ISSUE TITLE
results in README

### ISSUE THREAD

**Issue by rchikhi** [Piezoid/pugz#4]
add a table in the README with results (in MB/s) for e.g. counting lines and outputting whole text, versus gunzip

as results from the paper will likely be improved

**Comment by Piezoid** [comment]
Good idea, indeed.

There is few tweaks I want to try first.

I can benchmark on my 2011's 12 cores machine. Tell me if you have another idea.

There is also the CRC32 issue, since we have it disabled at the moment it wouldn't be completely fair to compare ourself to other implementations that compute it.

**Comment by rchikhi** [comment]
Good points. Any machine will do, really. And for CRC32, we'll just make a note (asterisk) to indicate this caveat (until CRC32 is implemented but i don't see it as high priority).
